apiVersion: v2
name: evroc-ccm
description: Kubernetes Cloud Controller Manager for the evroc cloud platform
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - cloud-controller-manager
  - ccm
  - evroc
  - kubernetes
  - topology
  - node-labeling
home: https://github.com/evroc-oss/evroc-ccm-driver
sources:
  - https://github.com/evroc-oss/evroc-ccm-driver
maintainers:
  - name: evroc Team
    email: support@evroc.com
icon: https://raw.githubusercontent.com/evroc-oss/evroc-ccm-driver/main/docs/images/evroc-logo.png
kubeVersion: ">=1.29.0-0"
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "false"
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/evroc-oss/evroc-ccm-driver
    - name: Source
      url: https://github.com/evroc-oss/evroc-ccm-driver
  catalog.cattle.io/display-name: evroc Cloud Controller Manager
  catalog.cattle.io/release-name: evroc-ccm
  catalog.cattle.io/namespace: evroc-system
  catalog.cattle.io/os: linux
